name: Base Image Build

on:
  push:

jobs:
  buildx:
    runs-on: self-hosted
    timeout-minutes: 1440
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        uses: docker/setup-buildx-action@v3
        id: build-base
        with:
          install: true
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64, linux/arm64/v8
          push: true
          tags: authsec/emre-bb-28:latest
